### ISSUE TITLE
AVI Viewing in 4.2.b and 4.2c

### ISSUE THREAD

**Issue by fewarren** [share-extras/media-viewers#17]
I have been able to get most of the media viewers working in two version of Community (4.2.b and 4.2.c). I have had to place the jar file in tomcat/webapps/shared/WEB-INF/lib as there seems to be problems in 4.2.b (didn't detect the jar) and 4.2.c (generated errors in IMAP subsystem) when I used tomcat/shared/lib. I have been able to successfully get ffmpeg installed and there are no ffmpeg errors in the log file. However, in all cases the AVI viewer fails.  The stack trace indicates that h264preview was not found in 4.2.c but I have not checked this out in 4.2.b yet.  There was one warning message in the stdout log file that was consistent in both versions that might be meaningful:

2013-07-15 15:34:54,155  WARN  [content.transform.AbstractContentTransformer2] [localhost-startStop-1] Property 'registry' has not been set.  Ignoring auto-registration: 
   transformer: ComplexContentTransformer[ average=0ms]

I could include a larger amount of log file from either version if it would be useful.  

I am very interested in getting Media-Viewers working.  They are important to our users. If you have a suggestion on where I go next, I would appreciate it.

Thanks for looking at this.

Fred

**Comment by wabson** [comment]
Hi Fred, firstly are you using the latest code? I made some changes yesterday for 4.2.c compatibility so it should be fine with that version now.

I would suggest focussing on one of the problems that you mention in this issue, and you can always open additional issues for the others.

**Comment by fewarren** [comment]
Will,

I am making progress. I reinstalled Community 4.2.c, on my Windows 7 system, got your latest media-viewers jar, put it into tomcat/shared/lib, setup ffmpeg, and turned on the debug trace. After doing the module installs, I uploaded an AVI file and tried to do a preview. The media-viewer conversion seemed to recognize it and ffmpeg was called for the conversion which was successful according to the log. However, the preview stalled with "Video conversion in progress, please wait" displayed. This message repeats whenever I try to do a preview.  Any thoughts?  Would you like the log file?

Fred

**Comment by wabson** [comment]
Hi Fred, for general discussion I would suggest using the [mailing list](http://groups.google.com/group/share-extras-devel). I have tested the most recent code against 4.2.c and I did not have any problems, so I believe this issue can be closed.
