### ISSUE TITLE
Unable to click on links in PDF/DOC/HTML file previews

### ISSUE THREAD

**Issue by Ashex** [share-extras/media-viewers#18]
It was recently brought to my attention that you cannot click on an html link inside a PDF, Microsoft Word Document, or HTML file. Alfresco Support was not able to replicate the issue in a vanilla environment (IE they could click on links) which indicates they may not be rendered properly via MediaPreview/PDFjs.

**Version**: Alfresco Enterprise 4.1.4

**Comment by wabson** [comment]
Duplicate of issue 8

**Comment by Ashex** [comment]
Oh Bollocks, I'll read the open tickets more carefully next time. Following #8
