### ISSUE TITLE
4.2.d Filmstrip view - js and css dependencies.

### ISSUE THREAD

**Issue by loftux** [share-extras/media-viewers#22]
We need to add js and css dependencies for view-render filmstrip. If this can be done programatically it is preferred. Else document how to override  
`<config evaluator="string-compare" condition="DocumentLibrary">` and `<view-renderers>` section. Unfortunately the entire section must be copy and pasted to override, I have found no way to just merge the dependencies section.

**Comment by wabson** [comment]
Do-able using an extensibility module?

**Comment by loftux** [comment]
This is now implemented as part of the module viewer configuration. When a viewer is enabled by its configuration option, this also loads the needed resources in filmstrip view.
