### ISSUE TITLE
Filmstrip view pagination interfere with PdfJs pagination

### ISSUE THREAD

**Issue by loftux** [share-extras/media-viewers#27]
To reproduce
1. Enable PdfJs in module configuration
2. Add more than 50 documents to a folder, some must be pdf:s
3. Switch to filmstrip view
4. View a pdf
5. Switch to view a non pdf documents
6. Try to use document list paginator
Expected: Navigate to next page
Actual: PdfJs picks up the navigation request and errors out since there is no pdf loaded, and the page requested doesn't exist.

**Comment by loftux** [comment]
Problem narrowed down to be the use of url hash #page that is also used for document library page navigation.  
This leads to
- The function onWindowHashChange picks up this change
- When a pdf is loaded in PdfJs it tries to make use of this hage and assumes this is the page that first should be displayed

We can solve this by
- Create a new page hash called pdfpage. This will however break all existing shortcuts users may have created.
- Detect that is the documentlibrary page and just skip the use of the page hash. Must then also hide the shortcut button. If we do this, coordingate with #12 .
- Just add code that checks if page number picked up from hash is larger than actual pages in pdf. If so, reset to highest available page number.  

I've tested the last option, this works, but if you are on page > 1 in the page listings, the display of the pdf starts on a page other than first page.

**Comment by loftux** [comment]
Further review of the issue and my conclusion is that we should disable the link button for all pages other than document details (or by configuration as in issue #12). For document library it is not possible to link to an individual file so that it is the one displayed in filmstrip view.

**Comment by wabson** [comment]
I agree with removing the link button for pages other than document-details. This can be done as part of the implemention of #12.
