### ISSUE TITLE
Endless reloading of shared node in an unauthorized session.

### ISSUE THREAD

**Issue by kamenf** [share-extras/media-viewers#29]
When node with video or audio content requiring thumbnail for preview is shared and the shared link is opened in unauthorized (logged out) session, page enters endless reloading loop.

What I can see so far is that json check for available thumbnails in plugin.display returns with status 401 (unauthorized).

This is observed with clear install of Community 4.2.e

**Comment by wabson** [comment]
What do you mean by the term _shared link_, in your description above? Do you have an example URL?

**Comment by kamenf** [comment]
By pressing "Shared" button in the document details page the system generates public link by which non registered users can access the document's content without account/login. Example link: http://127.0.0.1/share/s/yNyhHNl6Tr2CI7HXrfiEeA
The link to document thumbnails in this case is like: http://127.0.0.1/share/proxy/alfresco-noauth/api/internal/shared/node/yNyhHNl6Tr2CI7HXrfiEeA/content/thumbnails/h264preview

**Comment by kamenf** [comment]
Now creation of new thumbnails is not triggered for new uploads. See my comment in the code.
