### ISSUE TITLE
german properties translations upload?

### ISSUE THREAD

**Issue by jochem-i** [share-extras/media-viewers#35]
Hi,
I just translated the Java properties files into german. Any interest in including them in the media-viewers distribution? (Would I need to do a complete fork+pull-request etc. then?)

Regards
Jochem

**Comment by wabson** [comment]
Yes, please, Jochem, that would be great, if you could create a pull request off master then I will happily pull down to there

**Comment by wabson** [comment]
Fixed in #36

**Comment by wabson** [comment]
Thanks for the pull request, btw!

**Comment by jochem-i** [comment]
Hi Will,
the pleasure is all mine.
Regards
Jochem
