### ISSUE TITLE
When Share video - "Error: Could not load thumbnails list"

### ISSUE THREAD

**Issue by emardis2002** [share-extras/media-viewers#40]
Add-ons Media-Viewers - "Could not load thumbnails list" when share video.
Hi, when I share a video, clicking on the link the following error message appears me:
ERROR - Could not load thumbnails list

The link of the thumbnails is: http://site:8080/share/proxy/alfresco/api/node/nxNQt-6NSaySXcRZyxoF3g/content/thumbnails

![image](https://f.cloud.github.com/assets/6464619/1968214/4caf63f4-82df-11e3-9277-c5cdb78e694e.png)

---

 Alfresco   Web Script Status 404 - Not Found

The Web Script /alfresco/s/api/node/nxNQt-6NSaySXcRZyxoF3g/content/thumbnails has responded with a status of 404 - Not Found.

404 Description:     Requested resource is not available.

Message:    Cannot find object for NodeIdReference[storeRef=nxNQt-6NSaySXcRZyxoF3g://content,id=thumbnails]
Server: Community v4.2.0 (r56674-b4848) schema 6.033
Time:   21-ene-2014 17:46:45

Diagnostics:    Inspect Web Script (org/alfresco/cmis/item.get)

---

Thank,.

Alfresco Version
4.2.e
—
Alfresco Community v4.2.0 e(r56674-b4848) schema 6.033

**Comment by emardis2002** [comment]
Solution: Download lasted Release https://github.com/share-extras/media-viewers/releases

**Comment by wabson** [comment]
Thanks for the update, and yes this issue should indeed be fixed in the latest release of Media Viewers.

**Comment by emardis2002** [comment]
Wabson -> I am grateful to you, every post he saw his name appears....  :+1: P. 

Comment: README.md should change the file download link.
![image](https://f.cloud.github.com/assets/6464619/1987241/d98c83c4-8456-11e3-9519-ba36e2f54ae0.png)
