### ISSUE TITLE
code alfresco 5 ready?

### ISSUE THREAD

**Issue by bwakkie** [share-extras/media-viewers#49]
Is there already code that could work with alfresco 5?

I copied the media-viewers-2.6.2.jar from git/media-viewers/build/dist after  running ant -f project.xml dist-jar into my /opt/alfresco-5.0.d/tomcat/shared/lib directory. Restarted alfresco and enabled the modules. I was especially interested to replace the flash viewer.

Then restarted again just in case...

I did get a bunch of errors when trying to open a pdf so quickly removed all the modules and jar files. (I also got the odf viewer jar)

I took the fork from bforest/media-viewers as it seams more up to date.

I am not a java programmer so if I see java errors I run away... If I could help though I am happy to copy them in here ;-)

**Comment by loftux** [comment]
The PDFJs part (that replaces the flash viewer) of this viewer is now standard i Alfresco 5. So you do not need to install this add-on for that. See http://blogs.alfresco.com/wp/kevinr/2014/06/27/alfresco-community-5-0-a/
